### ISSUE TITLE
Make no-use-before-define rule an error

### ISSUE THREAD

**Issue by dcocchia** [instacart/javascript#12]
This rule seems to have slipped through the cracks. We can get some pretty serious bugs without this on. Can we enable in the shared eslint config?

**Comment by nathanmarks** [comment]
@dcocchia what about options?

https://eslint.org/docs/rules/no-use-before-define#options

**Comment by dcocchia** [comment]
Good question! Based on our convo, let's do `"functions": false` and the rest we can leave as default I think

**Comment by dcocchia** [comment]
Fixed in https://github.com/instacart/javascript/pull/13
